import './globals.css'
import { Inter } from 'next/font/google'
import { NextAuthProvider } from './providers'
import Navbar from '@/components/Navbar'
import { CounterContextProvider } from '@/context/Auth'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const data = await getData();

  console.log(data)


  return (
    <html lang="en">
      <body className={inter.className}>
        <CounterContextProvider initialState={{ count: data.count }}>
          <NextAuthProvider>
            <Navbar />
            {children}
          </NextAuthProvider>
        </CounterContextProvider>
      </body>
    </html>
  )
}


export async function getData() {
  return { count: 30 };
}