import Addr from '@/components/addr'
import Bear from '@/components/bear'
import Count from '@/components/count'
import Footer from '@/components/footer'
import Main from '@/components/main'
import Name from '@/components/name'
import Top from '@/components/top'
import View from '@/components/view'
import useZutand from '@/zustand/store'
import Head from 'next/head'


export default function Home() {
  

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Top />
      <Name />
      <Addr />
      <Bear />
      <View />
      <Count />
      <Main />
      <Footer />
    </>
  )
}
