import Head from 'next/head'

import styles from '@/styles/Home.module.css'
import Name from '@/components/name'
import Form from '@/components/form'



export default function Home() {
  

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Name />
        
        <Form />
      </main>
    </>
  )
}
